Repository Buddhad/contributors22, pull requests merged in 2022-10, with the labels that each got.

#9 feat: added footer and layout
  package-lock.json
  package.json
  public/images/Fintechtocat.png
  public/images/hula_loop_octodex03.gif
  src/App.css
  src/components/Footer.jsx
  src/main.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#11 Made changes in profile card.
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#12 Created README.md
  README.md
Labels: hacktoberfest22, hacktoberfest-accept

#18 added my card
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#23 Shaurya
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#24 added my profile card
  src/App.jsx
  src/components/Card.jsx
Labels: good first issue, hacktoberfest22, hacktoberfest-accept

#21 changed card details
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#28 Added a Header
  package-lock.json
  package.json
  public/hackto.svg
  src/App.jsx
  src/components/About.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/main.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#32 Added self card
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#33 adding contibutors card
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#35 added my contributors card
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#27 added font
  src/App.css
Labels: good first issue, hacktoberfest22, hacktoberfest-accept

#22 new card added in card.jsx
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accept

#41 improved navbar and changed hamburger cursor to pointer
  src/components/Header.css
  src/components/Header.jsx
Labels: enhancement, hacktoberfest22, hacktoberfest-accepted

#31 Feat: Added new contributors card
  src/App.css
  src/App.jsx
  src/components/Card.jsx
  src/components/Preloader.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#47 Added splash screen and fixed hamburger menu
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Header.jsx
Labels: enhancement, hacktoberfest22, hacktoberfest-accepted

#48 Fixed mobile responsiveness
  src/App.css
  src/App.jsx
  src/assets/grain-dark.png
Labels: hacktoberfest22, hacktoberfest-accepted

#49 add(Profile Card): Profile Card added
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#53 added black background
  src/App.css
  src/components/Card.jsx
  src/components/Footer.jsx
  src/components/card.css
Labels: hacktoberfest22, hacktoberfest-accepted

#54 Profile card added
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#56 Ankit test
  src/components/Card.jsx
  src/components/Header.css
Labels: hacktoberfest22, hacktoberfest-accepted

#59 Updated the cards
  src/components/Card.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#58 made changes to navbar
  src/components/Header.css
Labels: good first issue, hacktoberfest22, hacktoberfest-accepted

#63 About section
  src/components/About.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#65 Semi final
  src/components/Footer.jsx
  src/components/contact.jsx
Labels: hacktoberfest22, hacktoberfest-accepted

#66 updated footer
  src/components/Footer.jsx
Labels: hacktoberfest22, hacktoberfest-accepted
